dist:
    trusty

sudo:
    required

addons:
    postgresql: "9.5"

language:
    python

python:
    2.7

install:
    pip install tox codecov

script:
    tox
    codecov

services:
    postgresql

addons:
    postgresql: "9.5"

env:
    TEST_DB_HOST: "localhost"
    TEST_DB_NAME: "test"
    TEST_DB_USER: "postgres"
    TEST_DB_PASSWORD: ""