# Generated by Django 2.0 on 2018-07-02 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onfido_id', models.CharField(help_text='The id returned from the Onfido API.', max_length=40, unique=True, verbose_name='Onfido ID')),
                ('created_at', models.DateTimeField(blank=True, help_text='The timestamp returned from the Onfido API.', null=True)),
                ('raw', django_mysql.models.JSONField(blank=True, default=dict, help_text='The raw JSON returned from the API.', null=True)),
                ('user', models.OneToOneField(help_text='Django user that maps to this applicant.', on_delete=django.db.models.deletion.CASCADE, related_name='onfido_applicant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onfido_id', models.CharField(help_text='The id returned from the Onfido API.', max_length=40, unique=True, verbose_name='Onfido ID')),
                ('created_at', models.DateTimeField(blank=True, help_text='The timestamp returned from the Onfido API.', null=True)),
                ('raw', django_mysql.models.JSONField(blank=True, default=dict, help_text='The raw JSON returned from the API.', null=True)),
                ('status', models.CharField(blank=True, choices=[('Check', (('in_progress', 'In progress'), ('awaiting_applicant', 'Awaiting applicant'), ('complete', 'Complete'), ('withdrawn', 'Withdrawn'), ('paused', 'Paused'), ('reopened', 'Reopened'))), ('Report', (('awaiting_data', 'Awaiting data'), ('awaiting_approval', 'Awaiting approval'), ('complete', 'Complete'), ('withdrawn', 'Withdrawn'), ('paused', 'Paused'), ('cancelled', 'Cancelled')))], db_index=True, help_text='The current state of the check / report (from API).', max_length=20, null=True)),
                ('result', models.CharField(blank=True, choices=[('Check', (('clear', 'Clear'), ('consider', 'Consider'))), ('Report', (('clear', 'Clear'), ('consider', 'Consider'), ('unidentified', 'Unidentified')))], help_text='The final result of the check / reports (from API).', max_length=20, null=True)),
                ('updated_at', models.DateTimeField(blank=True, help_text='The timestamp of the most recent status change (from API).', null=True)),
                ('is_clear', models.NullBooleanField(default=None, help_text="True if the check / report is 'clear' (via API or manual override).")),
                ('check_type', models.CharField(choices=[('express', 'Express check'), ('standard', 'Standard check')], help_text='See https://documentation.onfido.com/#check-types', max_length=10)),
                ('applicant', models.ForeignKey(help_text='The applicant for whom the check is being made.', on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='onfido.Applicant')),
                ('user', models.ForeignKey(help_text='The Django user (denormalised from Applicant to make navigation easier).', on_delete=django.db.models.deletion.CASCADE, related_name='onfido_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onfido_id', models.CharField(help_text='The Onfido ID of the related resource.', max_length=40, verbose_name='Onfido ID')),
                ('resource_type', models.CharField(help_text='The resource_type returned from the API callback.', max_length=20)),
                ('action', models.CharField(help_text='The event name as returned from the API callback.', max_length=20)),
                ('status', models.CharField(help_text='The status of the object after the event.', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, help_text='The timestamp returned from the Onfido API.', null=True)),
                ('received_at', models.DateTimeField(help_text='The timestamp when the server received the event.')),
                ('raw', django_mysql.models.JSONField(blank=True, default=dict, help_text='The raw JSON returned from the API.', null=True)),
            ],
            options={
                'ordering': ['completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onfido_id', models.CharField(help_text='The id returned from the Onfido API.', max_length=40, unique=True, verbose_name='Onfido ID')),
                ('created_at', models.DateTimeField(blank=True, help_text='The timestamp returned from the Onfido API.', null=True)),
                ('raw', django_mysql.models.JSONField(blank=True, default=dict, help_text='The raw JSON returned from the API.', null=True)),
                ('status', models.CharField(blank=True, choices=[('Check', (('in_progress', 'In progress'), ('awaiting_applicant', 'Awaiting applicant'), ('complete', 'Complete'), ('withdrawn', 'Withdrawn'), ('paused', 'Paused'), ('reopened', 'Reopened'))), ('Report', (('awaiting_data', 'Awaiting data'), ('awaiting_approval', 'Awaiting approval'), ('complete', 'Complete'), ('withdrawn', 'Withdrawn'), ('paused', 'Paused'), ('cancelled', 'Cancelled')))], db_index=True, help_text='The current state of the check / report (from API).', max_length=20, null=True)),
                ('result', models.CharField(blank=True, choices=[('Check', (('clear', 'Clear'), ('consider', 'Consider'))), ('Report', (('clear', 'Clear'), ('consider', 'Consider'), ('unidentified', 'Unidentified')))], help_text='The final result of the check / reports (from API).', max_length=20, null=True)),
                ('updated_at', models.DateTimeField(blank=True, help_text='The timestamp of the most recent status change (from API).', null=True)),
                ('is_clear', models.NullBooleanField(default=None, help_text="True if the check / report is 'clear' (via API or manual override).")),
                ('report_type', models.CharField(choices=[('identity', 'Identity report'), ('document', 'Document report'), ('street_level', 'Street level report'), ('facial_similarity', 'Facial similarity report'), ('credit', 'Credit report'), ('criminal_history', 'Criminal history'), ('right_to_work', 'Right to work'), ('ssn_trace', 'SSN trace')], help_text='The name of the report - see https://documentation.onfido.com/#reports', max_length=20)),
                ('onfido_check', models.ForeignKey(help_text='Check to which this report is attached.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='onfido.Check')),
                ('user', models.ForeignKey(help_text='The Django user (denormalised from Applicant to make navigation easier).', on_delete=django.db.models.deletion.CASCADE, related_name='onfido_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
